import javax.swing.*;
import java.awt.*;

public class JPanelVarchar2 {
    private JTextField textField1;
    private JComboBox comboBox1;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JLabel label1 = new JLabel();
        label1.setText("Label");
        panel1.add(label1, BorderLayout.WEST);
        comboBox1 = new JComboBox();
        panel1.add(comboBox1, BorderLayout.CENTER);
        textField1 = new JTextField();
        panel1.add(textField1, BorderLayout.EAST);
    }
}
